global:
  country: DE
  org: My Org
  locality: Berlin
certs:
  - fileName: test
    CN: me.at.home
    CN_as_SAN: "false"
    CA: "false"
    SANs:
      - name: 127.0.0.1
      - name: 127.0.1.1
      - name: 10.0.0.1
  - CN: me.at.home
    SANs:
      - name: 10.0.0.2
